package com.newframe.entity.user;

import com.newframe.dto.user.response.UserRoleDTO;
import com.newframe.enums.PlatformBank;
import lombok.Data;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import java.math.BigDecimal;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table capital_flow
 *
 * @mbggenerated do_not_delete_during_merge
 */
@Data
@Entity
@Table(name = "capital_flow")
public class CapitalFlow {
    /**
     * 订单id
     * order_id
     */
    @Id
    @Column(name = "order_id")
    private Long orderId;

    /**
     * 用户uid
     * uid
     */
    @Column(name = "uid")
    private Long uid;

    /**
     * 商家名称
     * merchant_name
     */
    @Column(name = "merchant_name")
    private String merchantName;

    /**
     * 用户名称
     * user_name
     */
    @Column(name = "user_name")
    private String userName;

    /**
     * 用户手机号
     * user_phone_number
     */
    @Column(name = "user_phone_number")
    private String userPhoneNumber;

    /**
     * 用户银行卡
     * user_bank_number
     */
    @Column(name = "user_bank_number")
    private String userBankNumber;

    /**
     * 用户银行卡名称
     * user_bank_name
     */
    @Column(name = "user_bank_name")
    private String userBankName;

    /**
     * 用户银行卡详细名称
     * user_bank_detailed_name
     */
    @Column(name = "user_bank_detailed_name")
    private String userBankDetailedName;

    /**
     * 平台名称
     * platform_name
     */
    @Column(name = "platform_name")
    private String platformName;

    /**
     * 平台银行卡
     * platform_bank_number
     */
    @Column(name = "platform_bank_number")
    private String platformBankNumber;

    /**
     * 平台银行卡名称
     * platform_bank_name
     */
    @Column(name = "platform_bank_name")
    private String platformBankName;

    /**
     * 平台银行卡详细名称
     * platform_bank_detailed_name
     */
    @Column(name = "platform_bank_detailed_name")
    private String platformBankDetailedName;

    /**
     * 流水资金数量
     * amount
     */
    @Column(name = "amount")
    private BigDecimal amount;

    /**
     * 充值1，提现2
     * type
     */
    @Column(name = "type")
    private Integer type;

    /**
     * 订单状态
     * order_status
     */
    @Column(name = "order_status")
    private Integer orderStatus;

    /**
     * 审核人员id
     * check_uid
     */
    @Column(name = "check_uid")
    private Long checkUid;

    /**
     * 审核人员名称
     * check_name
     */
    @Column(name = "check_name")
    private String checkName;

    /**
     * 备注
     * remarks
     */
    @Column(name="remarks")
    private String remarks;

    /**
     * bank_money_flow表id
     * bank_money_flow_id
     */
    @Column(name = "bank_money_flow_id")
    private Long bankMoneyFlowId;

    /**
     * ctime
     * ctime
     */
    @Column(name = "ctime")
    private Integer ctime;

    /**
     * utime
     * utime
     */
    @Column(name = "utime")
    private Integer utime;

    public CapitalFlow() {
    }

    public CapitalFlow(UserBank userBank, UserRoleDTO role, BigDecimal amount, Integer status, Integer type) {
        PlatformBank platformBank = new PlatformBank();
        this.uid = userBank.getUid();
        this.merchantName = role.getName();
        this.userName = userBank.getBankUserName();
        this.userPhoneNumber = userBank.getBankPhoneNumber();
        this.userBankNumber = userBank.getBankNumber();
        this.userBankName = userBank.getBankName();
        this.userBankDetailedName = userBank.getBankDetailedName();
        this.platformName = platformBank.getPlatformName();
        this.platformBankNumber = platformBank.getPlatformBankNumber();
        this.platformBankName = platformBank.getPlatformBankName();
        this.platformBankDetailedName = platformBank.getPlatformBankDetailedName();
        this.amount = amount;
        this.type = type;
        this.orderStatus = status;
    }
}