package com.newframe.entity.user;

import lombok.Data;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * 供应商关系指定表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table merchant_appoint
 *
 * @mbggenerated do_not_delete_during_merge
 */
@Data
@Entity
@Table(name = "merchant_appoint")
public class MerchantAppoint {
    /**
     * id
     * id
     */
    @Id
    @Column(name = "id")
    private Long id;

    /**
     * 租赁商的uid
     * rent_merchant_uid
     */
    @Column(name = "rent_merchant_uid")
    private Long rentMerchantUid;

    /**
     * 供应商uid
     * supplier_uid
     */
    @Column(name = "supplier_uid")
    private Long supplierUid;

    /**
     * 创建时间
     * ctime
     */
    @Column(name = "ctime")
    private Integer ctime;

    /**
     * 更新时间
     * utime
     */
    @Column(name = "utime")
    private Integer utime;
}