package com.newframe.entity.user;

import com.newframe.enums.user.RoleStatusEnum;
import lombok.Data;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 *
 *  租赁商
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table user_rent_merchant
 *
 * @mbggenerated do_not_delete_during_merge
 */
@Data
@Entity
@Table(name = "user_rent_merchant")
public class UserRentMerchant {
    /**
     * 用户id
     * uid
     */
    @Id
    @Column(name = "uid")
    private Long uid;

    /**
     * 角色id 1.一级租赁商 2.二级租赁商
     * role_id
     */
    @Column(name = "role_id")
    private Integer roleId;

    /**
     * 商家名称
     * merchant_name
     */
    @Column(name = "merchant_name")
    private String merchantName;

    /**
     * 商家手机号
     * merchant_photo_number
     */
    @Column(name = "merchant_photo_number")
    private String merchantPhoneNumber;

    /**
     * 法人名称
     * legal_entity
     */
    @Column(name = "legal_entity")
    private String legalEntity;

    /**
     * 法人身份证号
     * legal_entity_id_number
     */
    @Column(name = "legal_entity_id_number")
    private String legalEntityIdNumber;

    /**
     * 商家地址
     * rent_merchant_address
     */
    @Column(name = "rent_merchant_address")
    private String rentMerchantAddress;

    /**
     * 营业职业编号
     * business_license_number
     */
    @Column(name = "business_license_number")
    private String businessLicenseNumber;

    /**
     * 营业执照文件
     * business_license_file
     */
    @Column(name = "business_license_file")
    private String businessLicenseFile;

    /**
     * 最高学历毕业证文件
     * highest_degree_diploma_file
     */
    @Column(name = "highest_degree_diploma_file")
    private String highestDegreeDiplomaFile;

    /**
     * 行驶证文件
     * driving_license_file
     */
    @Column(name = "driving_license_file")
    private String drivingLicenseFile;

    /**
     * 房产证或者租房合同文件
     * house_proprietary_certificate_file
     */
    @Column(name = "house_proprietary_certificate_file")
    private String houseProprietaryCertificateFile;

    /**
     * 角色状态
     * role_status
     */
    @Column(name = "role_status")
    private Integer roleStatus;

    /**
     *  隶属的一级租赁商uid
     *  parent_id
     */
    @Column(name = "parent_id")
    private Long parentId;

    /**
     * 省id
     * province_id
     */
    @Column(name = "province_id")
    private Integer provinceId;

    /**
     * 省名
     * province_name
     */
    @Column(name = "province_name")
    private String provinceName;

    /**
     * 市id
     * city_id
     */
    @Column(name = "city_id")
    private Integer cityId;

    /**
     * 市名
     * city_name
     */
    @Column(name = "city_name")
    private String cityName;

    /**
     * 县id
     * county_id
     */
    @Column(name = "county_id")
    private Integer countyId;

    /**
     * 县名
     * county_name
     */
    @Column(name = "county_name")
    private String countyName;

    /**
     * 详细地址
     * consignee_address
     */
    @Column(name = "consignee_address")
    private String consigneeAddress;

    /**
     * 是否指定供应商
     * appoint
     */
    @Column(name = "appoint")
    private Boolean appoint;

    /**
     * 创建时间
     * ctime
     */
    @Column(name = "ctime")
    private Integer ctime;

    /**
     * 更新时间
     * utime
     */
    @Column(name = "utime")
    private Integer utime;

    public UserRentMerchant() {
    }

    public UserRentMerchant(UserRoleApply userRoleApply) {
        this.uid = userRoleApply.getUid();
        this.roleId = userRoleApply.getRoleId();
        this.merchantName = userRoleApply.getMerchantName();
        this.merchantPhoneNumber = userRoleApply.getPhoneNumber();
        this.legalEntity = userRoleApply.getLegalEntity();
        this.legalEntityIdNumber = userRoleApply.getLegalEntityIdNumber();
        this.businessLicenseNumber = userRoleApply.getBusinessLicenseNumber();
        this.businessLicenseFile = userRoleApply.getBusinessLicenseFile();
        this.highestDegreeDiplomaFile = userRoleApply.getHighestDegreeDiplomaFile();
        this.drivingLicenseFile = userRoleApply.getDrivingLicenseFile();
        this.houseProprietaryCertificateFile = userRoleApply.getHouseProprietaryCertificateFile();
        this.roleStatus = RoleStatusEnum.NORMAL.getRoleStatue();
    }
}