package com.newframe.entity.user;

import lombok.Data;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 *
 *  用户密码
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table user_pwd
 *
 * @mbggenerated do_not_delete_during_merge
 */
@Data
@Entity
@Table(name = "user_pwd")
public class UserPwd {
    /**
     * 用户ID
     * uid
     */
    @Id
    @Column(name = "uid")
    private Long uid;

    /**
     * 登陆密码
     * login_pwd
     */
    @Column(name = "login_pwd")
    private String loginPwd;

    /**
     * 支付密码
     * pay_pwd
     */
    @Column(name = "pay_pwd")
    private String payPwd;

    /**
     * 创建时间
     * ctime
     */
    @Column(name = "ctime")
    private Integer ctime;

    /**
     * 更新时间
     * utime
     */
    @Column(name = "utime")
    private Integer utime;
}