package com.newframe.entity.user;

import lombok.Data;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 *
 *  用户角色申请
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table user_role_apply
 *
 * @mbggenerated do_not_delete_during_merge
 */
@Data
@Entity
@Table(name = "user_role_apply")
public class UserRoleApply {
    /**
     * 用户角色申请id
     * id
     */
    @Id
    @Column(name = "id")
    private Long id;

    /**
     * 用户ID
     * uid
     */
    @Column(name = "uid")
    private Long uid;

    /**
     * 角色id 1.一级租赁商 2.二级租赁商 3.资金方 4.供应商 5.资金方
     * role_id
     */
    @Column(name = "role_id")
    private Integer roleId;

    /**
     * 商家名称
     * merchant_name
     */
    @Column(name = "merchant_name")
    private String merchantName;

    /**
     * 法人名称
     * legal_entity
     */
    @Column(name = "legal_entity")
    private String legalEntity;

    /**
     * 法人身份证号
     * legal_entity_id_number
     */
    @Column(name = "legal_entity_id_number")
    private String legalEntityIdNumber;

    /**
     * 紧急联系人
     * top_contacts
     */
    @Column(name = "top_contacts")
    private String topContacts;

    /**
     * 紧急联系人手机号
     * top_contacts_phone_number
     */
    @Column(name = "top_contacts_phone_number")
    private String topContactsPhoneNumber;

    /**
     * 与紧急联系人关系
     * relationship
     */
    @Column(name = "relationship")
    private Integer relationship;

    /**
     * 营业职业编号
     * business_license_number
     */
    @Column(name = "business_license_number")
    private String businessLicenseNumber;

    /**
     * 营业执照文件
     * business_license_file
     */
    @Column(name = "business_license_file")
    private String businessLicenseFile;

    /**
     * 授权委托书文件  ,拼接的字符串
     * letter_of_attorney_file
     */
    @Column(name = "letter_of_attorney_file")
    private String letterOfAttorneyFile;

    /**
     * 经营资质文件   ,拼接的字符串
     * business_qualification_file
     */
    @Column(name = "business_qualification_file")
    private String businessQualificationFile;

    /**
     * 最高学历毕业证文件
     * highest_degree_diploma_file
     */
    @Column(name = "highest_degree_diploma_file")
    private String highestDegreeDiplomaFile;

    /**
     * 行驶证文件
     * driving_license_file
     */
    @Column(name = "driving_license_file")
    private String drivingLicenseFile;

    /**
     * 房产证或者租房合同文件
     * house_proprietary_certificate_file
     */
    @Column(name = "house_proprietary_certificate_file")
    private String houseProprietaryCertificateFile;

    /**
     * 申请状态
     * apply_status
     */
    @Column(name = "apply_status")
    private Integer applyStatus;

    /**
     * 备注
     * remarks
     */
    @Column(name = "remarks")
    private String remarks;

    /**
     * 创建时间
     * ctime
     */
    @Column(name = "ctime")
    private Integer ctime;

    /**
     * 更新时间
     * utime
     */
    @Column(name = "utime")
    private Integer utime;
}