package com.newframe.entity.user;

import lombok.Data;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 *
 *  用户实名信息
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table user_identity
 *
 * @mbggenerated do_not_delete_during_merge
 */
@Data
@Entity
@Table(name = "user_identity")
public class UserIdentity {
    /**
     * 用户ID
     * uid
     */
    @Id
    @Column(name = "uid")
    private Long uid;

    /**
     * 用户实名
     * real_name
     */
    @Column(name = "real_name")
    private String realName;

    /**
     * 用户国籍：1、中国，2、马来西亚，3、新加坡
     * nationality
     */
    @Column(name = "nationality")
    private Integer nationality;

    /**
     * 证件类型：1、中国身份证，2、外国证件
     * card_type
     */
    @Column(name = "card_type")
    private Integer cardType;

    /**
     * 证件号码
     * card_number
     */
    @Column(name = "card_number")
    private String cardNumber;

    /**
     * 正面照，存的是一个url地址
     * front_photo
     */
    @Column(name = "front_photo")
    private String frontPhoto;

    /**
     * 反面照，存的是一个url地址
     * back_photo
     */
    @Column(name = "back_photo")
    private String backPhoto;

    /**
     * 手持证件照，存的是一个url地址
     * hand_photo
     */
    @Column(name = "hand_photo")
    private String handPhoto;

    /**
     * 存的是一个url，用户认证时候的一段录音
     * user_video
     */
    @Column(name = "user_video")
    private String userVideo;

    /**
     * 创建时间
     * ctime
     */
    @Column(name = "ctime")
    private Integer ctime;

    /**
     * 更新时间
     * utime
     */
    @Column(name = "utime")
    private Integer utime;
}