package com.newframe.entity.user;

import lombok.Data;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 *
 *  登录历史
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table user_login_history
 *
 * @mbggenerated do_not_delete_during_merge
 */
@Data
@Entity
@Table(name = "user_login_history")
public class UserLoginHistory {
    /**
     * id
     * id
     */
    @Id
    @Column(name = "id")
    private Long id;

    /**
     * 用户id
     * uid
     */
    @Column(name = "uid")
    private Long uid;

    /**
     * 登陆方式：1、web，2、app
     * login_type
     */
    @Column(name = "login_type")
    private Integer loginType;

    /**
     * ip地址
     * ip
     */
    @Column(name = "ip")
    private String ip;

    /**
     * 创建时间
     * ctime
     */
    @Column(name = "ctime")
    private Integer ctime;

    /**
     * 更新时间
     * utime
     */
    @Column(name = "utime")
    private Integer utime;
}