package com.newframe.entity.user;

import lombok.Data;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 *
 *  出租方
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table user_hirer
 *
 * @mbggenerated do_not_delete_during_merge
 */
@Data
@Entity
@Table(name = "user_hirer")
public class UserHirer {
    /**
     * 用户ID
     * uid
     */
    @Id
    @Column(name = "uid")
    private Long uid;

    /**
     * 商家名称
     * merchant_name
     */
    @Column(name = "merchant_name")
    private String merchantName;

    /**
     * 法人名称
     * legal_entity
     */
    @Column(name = "legal_entity")
    private String legalEntity;

    /**
     * 法人身份证号
     * legal_entity_id_number
     */
    @Column(name = "legal_entity_id_number")
    private String legalEntityIdNumber;

    /**
     * 紧急联系人
     * top_contacts
     */
    @Column(name = "top_contacts")
    private String topContacts;

    /**
     * 紧急联系人手机号
     * top_contacts_phone_number
     */
    @Column(name = "top_contacts_phone_number")
    private String topContactsPhoneNumber;

    /**
     * 与紧急联系人关系
     * relationship
     */
    @Column(name = "relationship")
    private Integer relationship;

    /**
     * 营业职业编号
     * business_license_number
     */
    @Column(name = "business_license_number")
    private Long businessLicenseNumber;

    /**
     * 营业执照文件
     * business_license_file
     */
    @Column(name = "business_license_file")
    private String businessLicenseFile;

    /**
     * 角色状态
     * role_status
     */
    @Column(name = "role_status")
    private Integer roleStatus;

    /**
     * 创建时间
     * ctime
     */
    @Column(name = "ctime")
    private Integer ctime;

    /**
     * 更新时间
     * utime
     */
    @Column(name = "utime")
    private Integer utime;
}