package com.newframe.entity.user;

import lombok.Data;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 *
 *  用户角色关联
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table user_role
 *
 * @mbggenerated do_not_delete_during_merge
 */
@Data
@Entity
@Table(name = "user_role")
public class UserRole {
    /**
     * 用户角色关联id
     * id
     */
    @Id
    @Column(name = "id")
    private Long id;

    /**
     * 用户id
     * uid
     */
    @Column(name = "uid")
    private Long uid;

    /**
     * 角色id
     * role_id
     */
    @Column(name = "role_id")
    private Integer roleId;

    /**
     * 角色状态
     * role_status
     */
    @Column(name = "role_status")
    private Integer roleStatus;

    /**
     * 创建时间
     * ctime
     */
    @Column(name = "ctime")
    private Integer ctime;

    /**
     * 更新时间
     * utime
     */
    @Column(name = "utime")
    private Integer utime;
}